package com.example.gonzaloenrique.rgmm;

import android.app.Activity;
import android.os.Bundle;
import android.widget.ArrayAdapter;
import android.widget.AutoCompleteTextView;

import android.app.Activity;
import android.os.Bundle;
import android.widget.ArrayAdapter;
import android.widget.AutoCompleteTextView;
/**
 * Created by Gonzalo Enrique on 06/04/2015.
 */
public class Combis extends Activity {

    String[] combis = {
            "15 de Agosto S.A.",
            "24 De Diciembre S.R.L.",
            "3 de Octubre S.A.",
            "6 de Diciembre S.A.",
            "Alborada Transasil S.A.",
            "Alto la Luna S.A",
            "Amaru Sociedad Anonima",
            "Angeles Del Misti S.A.",
            "Angeles Del Sur (Etrasur S.A.)",
            "Audaces Tours S.A.",
            "Bella Vista Combi Express S.C.R.",
            "Benedicto Xvi S.A.",
            "Bus S.A.C. (Emsebus S.A.C.)",
            "Bus Service Independencia",
            "Buss Arequipa S.A.",
            "C.O.T.U.M. S.A.",
            "Campano Velarde y CIA S.A.",
            "Cerro Colorado S.A.C",
            "Cettar S.A.",
            "Characato S.A.",
            "Chavez Z E Hijos S.A.C.",
            "Christus S.A.C.",
            "Ciudad Municipal Arequipa S.A.",
            "Conan S.A.",
            "Continental S.A. (Transconsa)",
            "Corporacion Palermo Automotores S.A.",
            "COTAP S.A.",
            "COTASMIGPUA S.A.-ETCOS S.A.",
            "COTASPA S.A.",
            "Dean Valdivia S.A.",
            "Divino Niño Jesus San Camilo",
            "ECOPTRA S.A.",
            "El Calero S.R.Ltda",
            "El Chalan S.A.",
            "El Correcamino S.A.",
            "El Pacific S.A.",
            "El Rapido De Selva Alegre",
            "El Trome Guillen S.C.R.L.",
            "Escorpiones De Bustamante",
            "Espiritu Santo",
            "ETCOSAC",
            "ETMASA",
            "ETUPSSA S.A.",
            "Exenatru Sociedad Anonima",
            "Florian S.A.",
            "Garcilazo De La Vega",
            "Inka Terra Tour S.R.L.",
            "Inka Tours Express S.R.L.",
            "Joyino S.A.",
            "Juan XXIII S.R.LTDA.",
            "La Joya Del Sur S.A.C.",
            "La Perla S.R.LTDA.",
            "Las Begonias 1 S.A.",
            "Laser Jorge Chavez S.A.",
            "Litoral S.A. (Tralsa)",
            "Los Angeles Blancos S.R.L.",
            "Los Angeles De Ciudad De Dios",
            "Los Angeles De Villaba S.A",
            "Los Angeles Dorados De Hunter",
            "Los Ases Del Timon",
            "Los Canarios De Socabaya S.A.",
            "Los Claveles S.R.LTDA",
            "Los Delfines Azules S.A.",
            "Los Escorpiones S.A",
            "Los Pioneros",
            "Los Primeros Pioneros S.A.",
            "Los Ruiseñores S.A.",
            "Los Tres Volcanes S.A.",
            "Lutte E.I.R.Ltda",
            "Madariaga S.A.",
            "Marfil S.R.LTDA. S.A.",
            "Mariano Bustamante",
            "Miguel Grau Campiña S.A.",
            "Miguel Grau S.A.",
            "Miraflores S.A.-ETRAMPU S.A.",
            "Monterrey A S.A.",
            "Monterrey C S.A.",
            "Monterrey Vallecito S.A.",
            "Multiples De La Dorada S.A.",
            "Multiples Milagrosa De Chapi",
            "Multiples Virgen Adorada S.A.",
            "Nuestra Señora Virgen de los Remedios S.A.",
            "Nuevo Horizonte S.A. (Etnhsa).",
            "Nuevo Peru S.A.-ETRANPESA",
            "Ojo del Milagro",
            "Oriol S.A.",
            "Pais S.A. (Esm Transpais S.A.)",
            "Pampas De Polanco S.A.",
            "Peruarbo Buss S.A.",
            "Primavera-Tahuaycani S.A.",
            "Primor S.R.L.",
            "R.Coaguila Coaguila",
            "Rapido Kombis Independencia",
            "Reyes S.A.C.",
            "San Antonio De Padua",
            "San Isidro La Cano S.A.",
            "San Martin 43 S.A",
            "San Martin de Socabaya S.A.",
            "San Martin Express Bus S.A.",
            "San Martin S.A.",
            "Santa Clara S.R.L.",
            "Santa Rita De Siguas S.A.C.",
            "Santillana S.R.LTDA.",
            "Santillana Tours S.R.L",
            "Santo Domingo",
            "Santo Toribio De Mogrovejo",
            "Servico Especial Miraflores S.A.",
            "Señor de la Amargura S.A.",
            "Señor De Lampa S.A. Translampa",
            "Señor de Luren S.A.",
            "Señor del Gran Poder S.A.",
            "Sideral Tours Srl",
            "Sociedad Anonima Emtranpa S.A.",
            "SR. De La Joya S.R.LTDA",
            "Tiabaya S.A.",
            "Tiburcio Choque",
            "Tours F&F Srl",
            "TRANSMAPA S.A.",
            "Travic S.A.",
            "Turismo Quequeña S.A.C.",
            "Turismo San Isidro S.R.L.",
            "Turismo Y Expreso Florida",
            "Umachiri",
            "Unidos De Hunter S.A. Etunhsa",
            "Union Libertad S.A.C. Etulsac",
            "Urbanos La Joya S.A.C.",
            "Villa America del Sur del Peru S.A.A.",
            "Virgen Copacabana 2012 S.A",
            "Virgen de la candelaria S.A.",
            "Virgen De La Gloria S.A.",
            "Virgen De Polanco S.A.",
            "Volant Bus S.A.",
            "Waldos Inversiones Scrl.",
            "Yaquesan Sac",
            "Zamacola S.A.",
    };
    public void onCreate(Bundle savedInstanceState)
    {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.combis);

        ArrayAdapter<String> adapter = new ArrayAdapter<String>(this,android.R.layout.simple_dropdown_item_1line,combis);

        AutoCompleteTextView textView = (AutoCompleteTextView)findViewById(R.id.txtCombis);

        textView.setThreshold(3);
        textView.setAdapter(adapter);
    }
}
